### ISSUE TITLE
WebSocket autoreconnect

### ISSUE THREAD

**Issue by KrisJordan** [KrisJordan/trailhead#12]
After disconnecting (for example, shutting the server down); ideally the websocket should periodically try reconnecting (once per second).

While disconnected, the connection indicator should show an `error` color. While connected `primary`.

Steps to reproduce disconnection without auto-reconnect:

1. Load a module such as `hello_world`
2. Stop the server (wait a few seconds)
3. Restart the server

The connection should be reestablished, the connected indicator refreshed, and saving the module again should cause a reload of the module.

Note, a separate issue is now setup to change the connected/running status of a module when a disconnection is encountered.

**Comment by KrisJordan** [comment]
Hey @noahsmiths I just tried the reconnect branch and am not seeing the reconnect automatically happen without any user interaction.

When I click "Run" again on a demo like `hello_world`, it reconnects and works again.

Is this expected? Maybe react isn't redrawing and the reconnection did happen?

**Comment by noahsmiths** [comment]
@KrisJordan Oh that's weird, so in my testing I'd temporarily edited the Procfile so I could manually stop and start trailhead, while leaving caddy and vite running. My changes seem to work under those circumstances. However, when you use the Procfile to restart everything together, something breaks and the reconnect is no longer attempted.

In the interim, if you want to see how it was working in my testing, just commenting out the `server:` line in the Procfile and running trailhead manually in the demo directory from a separate terminal seems to work.

As for state of the running process, we could potentially just use the existing socket reducer which keeps the state of the long lived webhook, and if that readystate isn't equal to open, disable the PyProcessUI (the assumption being if the long lived webhook is disconnected, a run webhook won't work either). Otherwise, if we want to keep them separate, we could add a separate readystate state that follows the current runsocket, and similarly use that in PyProcessUI.

I have to run here for a bit, but will check back in on why this is once I'm home.

**Comment by KrisJordan** [comment]
Interesting, so I am wondering if this difference is somehow is due to Caddy still maintaining the active open socket despite the backend server it's proxying to shutting down? No rush here, just wanted to point out the behavior I was seeing when everything stopped and then came back.

**Comment by noahsmiths** [comment]
Yeah I think you're correct. I think what's happening is when caddy is still alive but the server isn't, caddy immediately rejects the connection, which then triggers a reconnect attempt client side. When caddy isn't running, at some point a websocket connect request hangs but never actually "fails", but because it's already been initialized, caddy has no way of recovering it (or even knowing about it) when it starts back up.
